USE [master]
GO
/****** Object:  Database [Blazor]    Script Date: 30/09/2020 17:00:07 ******/
CREATE DATABASE [Blazor]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Blazor', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Blazor.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Blazor_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Blazor_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Blazor] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Blazor].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Blazor] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Blazor] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Blazor] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Blazor] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Blazor] SET ARITHABORT OFF 
GO
ALTER DATABASE [Blazor] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Blazor] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Blazor] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Blazor] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Blazor] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Blazor] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Blazor] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Blazor] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Blazor] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Blazor] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Blazor] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Blazor] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Blazor] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Blazor] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Blazor] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Blazor] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Blazor] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Blazor] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Blazor] SET  MULTI_USER 
GO
ALTER DATABASE [Blazor] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Blazor] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Blazor] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Blazor] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Blazor] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Blazor] SET QUERY_STORE = OFF
GO
USE [Blazor]
GO
/****** Object:  Table [dbo].[UserData]    Script Date: 30/09/2020 17:00:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserData](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](320) NOT NULL,
	[PasswordHash] [nvarchar](72) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UC_User] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Blazor] SET  READ_WRITE 
GO
